---
- name: Ping Linux Server and Create User
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ping server
      ansible.builtin.ping:

    - name: Get hostname
      ansible.builtin.command: hostname
      register: hostname_output

    - name: Display hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ hostname_output.stdout }}"

    - name: Create user
      ansible.builtin.user:
        name: devuser
        state: present
        create_home: true
